name: Xray Docker Test

on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: 拉取本仓库
              uses: actions/checkout@v4

            - name: 构建镜像
              run: |
                  docker build -t xray-test:local .

            - name: 运行容器
              run: |
                  docker run -d --name xray-server \
                    -v $(pwd)/etc:/etc/xray \
                    -p 1080:1080 \
                    xray-test:local

            - name: 测试访问 ifconfig.me 并打印 IP
              run: |
                  echo "等待 3 秒确保服务启动"
                  sleep 3

                  echo "打印容器日志"
                  docker logs xray-server

                  echo "测试访问"
                  PROXY_IP=$(curl -s -x socks5h://127.0.0.1:1080 https://ifconfig.me/)
                  echo "当前IP为: $PROXY_IP"

                  # 验证返回内容是否不为空
                  if [ -z "$PROXY_IP" ]; then
                      echo "Test Failed: Could not get IP"
                      exit 1
                  fi

            - name: Cleanup
              if: always()
              run: docker rm -f xray-server
